/**
 * Route → asset consumption map for ECP v2 governed surfaces.
 * Every user-visible route/state must declare consumed asset keys.
 */
export const M55_ASSET_ROUTE_CONSUMPTION: Readonly<Record<string, readonly string[]>> = {
  'public.home': ['terminology.core', 'fence.free', 'fence.premium', 'trait.identity', 'plan.comparison_surface'],
  'public.root_redirect': ['terminology.core'],
  'public.how_m55_works': ['terminology.core', 'fence.free'],
  'public.ten_views': ['trait.identity', 'terminology.ten_qualities'],
  'public.pricing': ['plan.comparison_surface', 'product_truth.pricing', 'fence.premium'],
  'public.support': ['product_truth.pricing', 'safety.non_diagnostic'],
  'public.legal.terms': ['safety.legal'],
  'public.legal.privacy': ['safety.privacy'],
  'public.legal.tokushoho': ['product_truth.pricing', 'safety.legal'],
  'public.legal.refund': ['safety.legal'],
  'public.sign_in': ['terminology.core'],
  'public.sign_up': ['terminology.core'],
  'public.my': ['terminology.core'],
  'free.core.empty': ['free.funnel', 'terminology.core'],
  'free.core.intake': ['free.funnel', 'terminology.core'],
  'free.core.questions': ['free.questionnaire', 'terminology.core'],
  'free.core.answer_review': ['free.questionnaire', 'fence.free'],
  'free.core.result': ['free.result', 'trait.identity', 'fence.free', 'fence.premium', 'bridge.locked_preview', 'premium.experience.home_editorial_sample_v1'],
  'free.core.save': ['free.save', 'terminology.core'],
  'free.core.rerun': ['free.funnel', 'terminology.core'],
  'free.core.share': ['share.card', 'trait.identity'],
  'shared.entry': ['share.card', 'trait.identity', 'fence.free'],
  'shared.entry.invalid': ['share.card', 'terminology.core'],
  'shared.og': ['share.card', 'trait.identity'],
  'premium.dtr_index': ['premium.funnel', 'fence.premium', 'premium.experience.home_editorial_sample_v1'],
  'premium.lp.intro': ['fence.premium', 'trait.identity', 'bridge.locked_preview', 'premium.experience.home_editorial_sample_v1'],
  'premium.lp.need_free': ['free.funnel', 'fence.premium', 'premium.experience.home_editorial_sample_v1'],
  'premium.lp.questions': ['premium.questionnaire', 'fence.premium', 'premium.experience.home_editorial_sample_v1'],
  'premium.lp.answer_review': ['premium.questionnaire', 'fence.premium', 'premium.experience.home_editorial_sample_v1'],
  'premium.lp.plans': ['plan.comparison_surface', 'product_truth.pricing', 'premium.experience.home_editorial_sample_v1'],
  'premium.lp.upgrade': ['plan.comparison_surface', 'product_truth.upgrade', 'premium.experience.home_editorial_sample_v1'],
  'premium.lp.checkout': ['premium.funnel', 'plan.comparison_surface', 'safety.non_diagnostic', 'premium.experience.home_editorial_sample_v1'],
  'premium.processing': ['premium.funnel', 'premium.experience.home_editorial_sample_v1'],
  'premium.purchase_success': ['premium.funnel', 'terminology.premium_product', 'premium.experience.home_editorial_sample_v1'],
  'purchased.reader': ['individualization.paid_report_internal', 'premium.experience.home_editorial_sample_v1'],
  'legacy.tarot': ['terminology.core'],
  'legacy.ai_chat': ['terminology.core'],
  'legacy.today': ['terminology.core'],
  'legacy.weekly': ['terminology.core'],
  'legacy.calendar': ['terminology.core'],
  'legacy.ai_calendar': ['terminology.core'],
  'legacy.meter': ['terminology.core'],
  'legacy.reply': ['terminology.core'],
  'legacy.reply_result': ['terminology.core'],
  'legacy.synastry': ['terminology.core'],
  'legacy.synastry.confirm': ['terminology.core'],
  'legacy.synastry.success': ['terminology.core'],
  'legacy.synastry.report': ['terminology.core'],
  'prototype.hub': ['terminology.core'],
  'dev.previews': ['terminology.core'],
} as const;

export function assetKeysForRoute(routeId: string): readonly string[] {
  return M55_ASSET_ROUTE_CONSUMPTION[routeId] ?? [];
}
