/** Audit-frozen cross-surface birthday SSOT expectations. Source: divination-golden-matrix-audit.ts --json */
export type BirthdaySsotCertificationStatus = 'CERTIFIED' | 'REVIEW_REQUIRED' | 'INVARIANT_ONLY';

export type BirthdaySsotFrozenCase = {
  case_id: string;
  certification_status: BirthdaySsotCertificationStatus;
  birthDate: string;
  birthTime: string | null;
  birthTimeUnknown: boolean;
  country: string;
  timezone: string;
  stemLaneIndex: number;
  stemChar: string;
  publicTitle: string;
  imagePath: string;
  calculationMode: 'full' | 'unknown_time_noon' | 'tz_fallback_utc';
  errorCode: null;
  expectedCoreLabel: string;
  expectedCoreType: string;
  expectedCoreSummary: string;
  expectedWorkStyleSummary: string;
  expectedPaidIdentityFingerprint: string;
  expectedPaidCompositionFingerprint: string;
  expectedPaidEssenceFingerprint: string;
  contentSource: 'TYPE_CATALOG+STEM_BODIES';
};

export const BIRTHDAY_SSOT_AUDIT_FREEZE_GENERATED_AT = '2026-06-22';

export const BIRTHDAY_SSOT_CROSS_SURFACE_AUDIT_FREEZE: readonly BirthdaySsotFrozenCase[] = [
  {
    "case_id": "DM-GX-01",
    "birthDate": "1983-02-28",
    "birthTime": null,
    "birthTimeUnknown": true,
    "country": "JP",
    "timezone": "Asia/Tokyo",
    "stemLaneIndex": 9,
    "stemChar": "癸",
    "publicTitle": "アナリスト",
    "imagePath": "/ten-views/analyst.webp",
    "calculationMode": "unknown_time_noon",
    "errorCode": null,
    "certification_status": "CERTIFIED",
    "expectedCoreLabel": "統合設計型",
    "expectedCoreType": "TYPE_10",
    "expectedCoreSummary": "バラバラの要素を一つの形にまとめ、全体として意味を持たせようとする本質です。統合と設計の観測が前に出やすいタイプです。",
    "expectedWorkStyleSummary": "バラバラの要素をひとつの流れにまとめ、全体の見通しが立つときに力を発揮しやすい観測です。",
    "expectedPaidIdentityFingerprint": "djb2:73559756",
    "expectedPaidCompositionFingerprint": "djb2:72fe3c33",
    "expectedPaidEssenceFingerprint": "djb2:aad6ddcf",
    "contentSource": "TYPE_CATALOG+STEM_BODIES"
  },
  {
    "case_id": "DM-ADJ-1992-12-18",
    "birthDate": "1992-12-18",
    "birthTime": null,
    "birthTimeUnknown": true,
    "country": "JP",
    "timezone": "Asia/Tokyo",
    "stemLaneIndex": 0,
    "stemChar": "甲",
    "publicTitle": "プレジデント",
    "imagePath": "/ten-views/president.webp",
    "calculationMode": "unknown_time_noon",
    "errorCode": null,
    "certification_status": "REVIEW_REQUIRED",
    "expectedCoreLabel": "観測深化型",
    "expectedCoreType": "TYPE_01",
    "expectedCoreSummary": "表面で終わらず、小さな差分や意味の層を拾い上げて深めようとする本質です。静かに精度を上げるタイプの観測です。",
    "expectedWorkStyleSummary": "ひとりで深く向き合える時間と、静かな余白があるときに力が出やすい観測です。割り込みが少ないほど輪郭がはっきりします。",
    "expectedPaidIdentityFingerprint": "djb2:76b981e0",
    "expectedPaidCompositionFingerprint": "djb2:88a1863b",
    "expectedPaidEssenceFingerprint": "djb2:4b548610",
    "contentSource": "TYPE_CATALOG+STEM_BODIES"
  },
  {
    "case_id": "DM-ADJ-1992-12-19",
    "birthDate": "1992-12-19",
    "birthTime": null,
    "birthTimeUnknown": true,
    "country": "JP",
    "timezone": "Asia/Tokyo",
    "stemLaneIndex": 1,
    "stemChar": "乙",
    "publicTitle": "プランナー",
    "imagePath": "/ten-views/planner.webp",
    "calculationMode": "unknown_time_noon",
    "errorCode": null,
    "certification_status": "REVIEW_REQUIRED",
    "expectedCoreLabel": "共鳴受容型",
    "expectedCoreType": "TYPE_02",
    "expectedCoreSummary": "相手の温度や空気を受け取り、関係の中でバランスを保とうとする本質です。調整と受容の観測が強いタイプです。",
    "expectedWorkStyleSummary": "近い人との距離を整えながら、少しずつ前に進めるときに力が出しやすい観測です。",
    "expectedPaidIdentityFingerprint": "djb2:0d095bac",
    "expectedPaidCompositionFingerprint": "djb2:bf0ccb72",
    "expectedPaidEssenceFingerprint": "djb2:835fa585",
    "contentSource": "TYPE_CATALOG+STEM_BODIES"
  },
  {
    "case_id": "DM-ADJ-1992-12-20",
    "birthDate": "1992-12-20",
    "birthTime": null,
    "birthTimeUnknown": true,
    "country": "JP",
    "timezone": "Asia/Tokyo",
    "stemLaneIndex": 2,
    "stemChar": "丙",
    "publicTitle": "インフルエンサー",
    "imagePath": "/ten-views/influencer.webp",
    "calculationMode": "unknown_time_noon",
    "errorCode": null,
    "certification_status": "REVIEW_REQUIRED",
    "expectedCoreLabel": "構造探求型",
    "expectedCoreType": "TYPE_03",
    "expectedCoreSummary": "物事の骨格や因果をつかみ、筋の良い形に直そうとする本質です。整理と構造化の観測が前に出やすいタイプです。",
    "expectedWorkStyleSummary": "散らかったことを順番に整え、自分が納得できる形に近づけられるときに伸びやすい観測です。",
    "expectedPaidIdentityFingerprint": "djb2:dde14f2b",
    "expectedPaidCompositionFingerprint": "djb2:52a04920",
    "expectedPaidEssenceFingerprint": "djb2:ea81dd2c",
    "contentSource": "TYPE_CATALOG+STEM_BODIES"
  },
  {
    "case_id": "DM-MON-2000-01-15",
    "birthDate": "2000-01-15",
    "birthTime": null,
    "birthTimeUnknown": true,
    "country": "JP",
    "timezone": "Asia/Tokyo",
    "stemLaneIndex": 4,
    "stemChar": "戊",
    "publicTitle": "マネージャー",
    "imagePath": "/ten-views/manager.webp",
    "calculationMode": "unknown_time_noon",
    "errorCode": null,
    "certification_status": "REVIEW_REQUIRED",
    "expectedCoreLabel": "調和観測型",
    "expectedCoreType": "TYPE_05",
    "expectedCoreSummary": "全体のバランスを見ながら、衝突をほどいて進めようとする本質です。調和と観測の両立が出やすいタイプです。",
    "expectedWorkStyleSummary": "近い人との距離や、日々の流れを整えながら進めるときに伸びやすいです。",
    "expectedPaidIdentityFingerprint": "djb2:4cc440b1",
    "expectedPaidCompositionFingerprint": "djb2:f563682d",
    "expectedPaidEssenceFingerprint": "djb2:6bc4cdee",
    "contentSource": "TYPE_CATALOG+STEM_BODIES"
  },
  {
    "case_id": "DM-MON-2000-02-15",
    "birthDate": "2000-02-15",
    "birthTime": null,
    "birthTimeUnknown": true,
    "country": "JP",
    "timezone": "Asia/Tokyo",
    "stemLaneIndex": 5,
    "stemChar": "己",
    "publicTitle": "プロデューサー",
    "imagePath": "/ten-views/producer.webp",
    "calculationMode": "unknown_time_noon",
    "errorCode": null,
    "certification_status": "REVIEW_REQUIRED",
    "expectedCoreLabel": "直観展開型",
    "expectedCoreType": "TYPE_06",
    "expectedCoreSummary": "ひらめきと勢いで仮説を広げ、場を前に動かそうとする本質です。展開と熱量の観測が前に出やすいタイプです。",
    "expectedWorkStyleSummary": "近い人との場に熱量があり、反応が返ってくるときに力を発揮しやすい観測です。",
    "expectedPaidIdentityFingerprint": "djb2:d803f226",
    "expectedPaidCompositionFingerprint": "djb2:d5370ee6",
    "expectedPaidEssenceFingerprint": "djb2:d4b767fd",
    "contentSource": "TYPE_CATALOG+STEM_BODIES"
  },
  {
    "case_id": "DM-MON-2000-03-15",
    "birthDate": "2000-03-15",
    "birthTime": null,
    "birthTimeUnknown": true,
    "country": "JP",
    "timezone": "Asia/Tokyo",
    "stemLaneIndex": 4,
    "stemChar": "戊",
    "publicTitle": "マネージャー",
    "imagePath": "/ten-views/manager.webp",
    "calculationMode": "unknown_time_noon",
    "errorCode": null,
    "certification_status": "REVIEW_REQUIRED",
    "expectedCoreLabel": "調和観測型",
    "expectedCoreType": "TYPE_05",
    "expectedCoreSummary": "全体のバランスを見ながら、衝突をほどいて進めようとする本質です。調和と観測の両立が出やすいタイプです。",
    "expectedWorkStyleSummary": "近い人との距離や、日々の流れを整えながら進めるときに伸びやすいです。",
    "expectedPaidIdentityFingerprint": "djb2:4cc440b1",
    "expectedPaidCompositionFingerprint": "djb2:f563682d",
    "expectedPaidEssenceFingerprint": "djb2:4148b842",
    "contentSource": "TYPE_CATALOG+STEM_BODIES"
  },
  {
    "case_id": "DM-MON-2000-04-15",
    "birthDate": "2000-04-15",
    "birthTime": null,
    "birthTimeUnknown": true,
    "country": "JP",
    "timezone": "Asia/Tokyo",
    "stemLaneIndex": 5,
    "stemChar": "己",
    "publicTitle": "プロデューサー",
    "imagePath": "/ten-views/producer.webp",
    "calculationMode": "unknown_time_noon",
    "errorCode": null,
    "certification_status": "REVIEW_REQUIRED",
    "expectedCoreLabel": "直観展開型",
    "expectedCoreType": "TYPE_06",
    "expectedCoreSummary": "ひらめきと勢いで仮説を広げ、場を前に動かそうとする本質です。展開と熱量の観測が前に出やすいタイプです。",
    "expectedWorkStyleSummary": "近い人との場に熱量があり、反応が返ってくるときに力を発揮しやすい観測です。",
    "expectedPaidIdentityFingerprint": "djb2:d803f226",
    "expectedPaidCompositionFingerprint": "djb2:d5370ee6",
    "expectedPaidEssenceFingerprint": "djb2:a6fd5eae",
    "contentSource": "TYPE_CATALOG+STEM_BODIES"
  },
  {
    "case_id": "DM-MON-2000-05-15",
    "birthDate": "2000-05-15",
    "birthTime": null,
    "birthTimeUnknown": true,
    "country": "JP",
    "timezone": "Asia/Tokyo",
    "stemLaneIndex": 5,
    "stemChar": "己",
    "publicTitle": "プロデューサー",
    "imagePath": "/ten-views/producer.webp",
    "calculationMode": "unknown_time_noon",
    "errorCode": null,
    "certification_status": "REVIEW_REQUIRED",
    "expectedCoreLabel": "直観展開型",
    "expectedCoreType": "TYPE_06",
    "expectedCoreSummary": "ひらめきと勢いで仮説を広げ、場を前に動かそうとする本質です。展開と熱量の観測が前に出やすいタイプです。",
    "expectedWorkStyleSummary": "近い人との場に熱量があり、反応が返ってくるときに力を発揮しやすい観測です。",
    "expectedPaidIdentityFingerprint": "djb2:d803f226",
    "expectedPaidCompositionFingerprint": "djb2:d5370ee6",
    "expectedPaidEssenceFingerprint": "djb2:de58b3d1",
    "contentSource": "TYPE_CATALOG+STEM_BODIES"
  },
  {
    "case_id": "DM-MON-2000-06-15",
    "birthDate": "2000-06-15",
    "birthTime": null,
    "birthTimeUnknown": true,
    "country": "JP",
    "timezone": "Asia/Tokyo",
    "stemLaneIndex": 6,
    "stemChar": "庚",
    "publicTitle": "エグゼキューター",
    "imagePath": "/ten-views/executor.webp",
    "calculationMode": "unknown_time_noon",
    "errorCode": null,
    "certification_status": "REVIEW_REQUIRED",
    "expectedCoreLabel": "核心追究型",
    "expectedCoreType": "TYPE_07",
    "expectedCoreSummary": "表面で終わらず、物事の核と意味をつかもうとする本質です。深さと筋の良さを優先する観測が強いタイプです。",
    "expectedWorkStyleSummary": "深く考えて整えられる時間と、自分の範囲が分かるときに力を発揮しやすい観測です。",
    "expectedPaidIdentityFingerprint": "djb2:61f81f88",
    "expectedPaidCompositionFingerprint": "djb2:7fe09bf1",
    "expectedPaidEssenceFingerprint": "djb2:dd265df8",
    "contentSource": "TYPE_CATALOG+STEM_BODIES"
  },
  {
    "case_id": "DM-MON-2000-07-15",
    "birthDate": "2000-07-15",
    "birthTime": null,
    "birthTimeUnknown": true,
    "country": "JP",
    "timezone": "Asia/Tokyo",
    "stemLaneIndex": 6,
    "stemChar": "庚",
    "publicTitle": "エグゼキューター",
    "imagePath": "/ten-views/executor.webp",
    "calculationMode": "unknown_time_noon",
    "errorCode": null,
    "certification_status": "REVIEW_REQUIRED",
    "expectedCoreLabel": "核心追究型",
    "expectedCoreType": "TYPE_07",
    "expectedCoreSummary": "表面で終わらず、物事の核と意味をつかもうとする本質です。深さと筋の良さを優先する観測が強いタイプです。",
    "expectedWorkStyleSummary": "深く考えて整えられる時間と、自分の範囲が分かるときに力を発揮しやすい観測です。",
    "expectedPaidIdentityFingerprint": "djb2:61f81f88",
    "expectedPaidCompositionFingerprint": "djb2:7fe09bf1",
    "expectedPaidEssenceFingerprint": "djb2:e7e166ef",
    "contentSource": "TYPE_CATALOG+STEM_BODIES"
  },
  {
    "case_id": "DM-MON-2000-08-15",
    "birthDate": "2000-08-15",
    "birthTime": null,
    "birthTimeUnknown": true,
    "country": "JP",
    "timezone": "Asia/Tokyo",
    "stemLaneIndex": 7,
    "stemChar": "辛",
    "publicTitle": "デザイナー",
    "imagePath": "/ten-views/designer.webp",
    "calculationMode": "unknown_time_noon",
    "errorCode": null,
    "certification_status": "REVIEW_REQUIRED",
    "expectedCoreLabel": "推進整理型",
    "expectedCoreType": "TYPE_08",
    "expectedCoreSummary": "迷いを減らし、次の一手を決めて進めようとする本質です。実行と整理のバランスが取りやすいタイプの観測です。",
    "expectedWorkStyleSummary": "優先順位が見え、完了まで自分のペースで進められるときに力を出しやすいです。",
    "expectedPaidIdentityFingerprint": "djb2:e2e494d4",
    "expectedPaidCompositionFingerprint": "djb2:28b34cf6",
    "expectedPaidEssenceFingerprint": "djb2:9ce9f3aa",
    "contentSource": "TYPE_CATALOG+STEM_BODIES"
  },
  {
    "case_id": "DM-MON-2000-09-15",
    "birthDate": "2000-09-15",
    "birthTime": null,
    "birthTimeUnknown": true,
    "country": "JP",
    "timezone": "Asia/Tokyo",
    "stemLaneIndex": 8,
    "stemChar": "壬",
    "publicTitle": "グローバルリーダー",
    "imagePath": "/ten-views/global-leader.webp",
    "calculationMode": "unknown_time_noon",
    "errorCode": null,
    "certification_status": "REVIEW_REQUIRED",
    "expectedCoreLabel": "関係洞察型",
    "expectedCoreType": "TYPE_09",
    "expectedCoreSummary": "人と人の間に起きていることを読み取り、関係性の質を上げようとする本質です。洞察と配慮の観測が強いタイプです。",
    "expectedWorkStyleSummary": "近い人の言葉や距離に関わる場面で、力を発揮しやすい観測です。",
    "expectedPaidIdentityFingerprint": "djb2:5ad4ecc0",
    "expectedPaidCompositionFingerprint": "djb2:b7b5465a",
    "expectedPaidEssenceFingerprint": "djb2:42eaf74f",
    "contentSource": "TYPE_CATALOG+STEM_BODIES"
  },
  {
    "case_id": "DM-MON-2000-10-15",
    "birthDate": "2000-10-15",
    "birthTime": null,
    "birthTimeUnknown": true,
    "country": "JP",
    "timezone": "Asia/Tokyo",
    "stemLaneIndex": 8,
    "stemChar": "壬",
    "publicTitle": "グローバルリーダー",
    "imagePath": "/ten-views/global-leader.webp",
    "calculationMode": "unknown_time_noon",
    "errorCode": null,
    "certification_status": "REVIEW_REQUIRED",
    "expectedCoreLabel": "関係洞察型",
    "expectedCoreType": "TYPE_09",
    "expectedCoreSummary": "人と人の間に起きていることを読み取り、関係性の質を上げようとする本質です。洞察と配慮の観測が強いタイプです。",
    "expectedWorkStyleSummary": "近い人の言葉や距離に関わる場面で、力を発揮しやすい観測です。",
    "expectedPaidIdentityFingerprint": "djb2:5ad4ecc0",
    "expectedPaidCompositionFingerprint": "djb2:b7b5465a",
    "expectedPaidEssenceFingerprint": "djb2:1ad3b260",
    "contentSource": "TYPE_CATALOG+STEM_BODIES"
  },
  {
    "case_id": "DM-MON-2000-11-15",
    "birthDate": "2000-11-15",
    "birthTime": null,
    "birthTimeUnknown": true,
    "country": "JP",
    "timezone": "Asia/Tokyo",
    "stemLaneIndex": 9,
    "stemChar": "癸",
    "publicTitle": "アナリスト",
    "imagePath": "/ten-views/analyst.webp",
    "calculationMode": "unknown_time_noon",
    "errorCode": null,
    "certification_status": "REVIEW_REQUIRED",
    "expectedCoreLabel": "統合設計型",
    "expectedCoreType": "TYPE_10",
    "expectedCoreSummary": "バラバラの要素を一つの形にまとめ、全体として意味を持たせようとする本質です。統合と設計の観測が前に出やすいタイプです。",
    "expectedWorkStyleSummary": "バラバラの要素をひとつの流れにまとめ、全体の見通しが立つときに力を発揮しやすい観測です。",
    "expectedPaidIdentityFingerprint": "djb2:73559756",
    "expectedPaidCompositionFingerprint": "djb2:72fe3c33",
    "expectedPaidEssenceFingerprint": "djb2:079af6ad",
    "contentSource": "TYPE_CATALOG+STEM_BODIES"
  },
  {
    "case_id": "DM-MON-2000-12-15",
    "birthDate": "2000-12-15",
    "birthTime": null,
    "birthTimeUnknown": true,
    "country": "JP",
    "timezone": "Asia/Tokyo",
    "stemLaneIndex": 9,
    "stemChar": "癸",
    "publicTitle": "アナリスト",
    "imagePath": "/ten-views/analyst.webp",
    "calculationMode": "unknown_time_noon",
    "errorCode": null,
    "certification_status": "REVIEW_REQUIRED",
    "expectedCoreLabel": "統合設計型",
    "expectedCoreType": "TYPE_10",
    "expectedCoreSummary": "バラバラの要素を一つの形にまとめ、全体として意味を持たせようとする本質です。統合と設計の観測が前に出やすいタイプです。",
    "expectedWorkStyleSummary": "バラバラの要素をひとつの流れにまとめ、全体の見通しが立つときに力を発揮しやすい観測です。",
    "expectedPaidIdentityFingerprint": "djb2:73559756",
    "expectedPaidCompositionFingerprint": "djb2:72fe3c33",
    "expectedPaidEssenceFingerprint": "djb2:3743edb9",
    "contentSource": "TYPE_CATALOG+STEM_BODIES"
  },
  {
    "case_id": "DM-SOL-2024-02-03",
    "birthDate": "2024-02-03",
    "birthTime": "12:00",
    "birthTimeUnknown": false,
    "country": "JP",
    "timezone": "Asia/Tokyo",
    "stemLaneIndex": 9,
    "stemChar": "癸",
    "publicTitle": "アナリスト",
    "imagePath": "/ten-views/analyst.webp",
    "calculationMode": "full",
    "errorCode": null,
    "certification_status": "CERTIFIED",
    "expectedCoreLabel": "統合設計型",
    "expectedCoreType": "TYPE_10",
    "expectedCoreSummary": "バラバラの要素を一つの形にまとめ、全体として意味を持たせようとする本質です。統合と設計の観測が前に出やすいタイプです。",
    "expectedWorkStyleSummary": "バラバラの要素をひとつの流れにまとめ、全体の見通しが立つときに力を発揮しやすい観測です。",
    "expectedPaidIdentityFingerprint": "djb2:73559756",
    "expectedPaidCompositionFingerprint": "djb2:72fe3c33",
    "expectedPaidEssenceFingerprint": "djb2:118bfb74",
    "contentSource": "TYPE_CATALOG+STEM_BODIES"
  },
  {
    "case_id": "DM-SOL-2024-02-04",
    "birthDate": "2024-02-04",
    "birthTime": "12:00",
    "birthTimeUnknown": false,
    "country": "JP",
    "timezone": "Asia/Tokyo",
    "stemLaneIndex": 0,
    "stemChar": "甲",
    "publicTitle": "プレジデント",
    "imagePath": "/ten-views/president.webp",
    "calculationMode": "full",
    "errorCode": null,
    "certification_status": "CERTIFIED",
    "expectedCoreLabel": "観測深化型",
    "expectedCoreType": "TYPE_01",
    "expectedCoreSummary": "表面で終わらず、小さな差分や意味の層を拾い上げて深めようとする本質です。静かに精度を上げるタイプの観測です。",
    "expectedWorkStyleSummary": "ひとりで深く向き合える時間と、静かな余白があるときに力が出やすい観測です。割り込みが少ないほど輪郭がはっきりします。",
    "expectedPaidIdentityFingerprint": "djb2:76b981e0",
    "expectedPaidCompositionFingerprint": "djb2:88a1863b",
    "expectedPaidEssenceFingerprint": "djb2:501ebd8b",
    "contentSource": "TYPE_CATALOG+STEM_BODIES"
  },
  {
    "case_id": "DM-SOL-2024-02-05",
    "birthDate": "2024-02-05",
    "birthTime": "12:00",
    "birthTimeUnknown": false,
    "country": "JP",
    "timezone": "Asia/Tokyo",
    "stemLaneIndex": 1,
    "stemChar": "乙",
    "publicTitle": "プランナー",
    "imagePath": "/ten-views/planner.webp",
    "calculationMode": "full",
    "errorCode": null,
    "certification_status": "CERTIFIED",
    "expectedCoreLabel": "共鳴受容型",
    "expectedCoreType": "TYPE_02",
    "expectedCoreSummary": "相手の温度や空気を受け取り、関係の中でバランスを保とうとする本質です。調整と受容の観測が強いタイプです。",
    "expectedWorkStyleSummary": "近い人との距離を整えながら、少しずつ前に進めるときに力が出しやすい観測です。",
    "expectedPaidIdentityFingerprint": "djb2:0d095bac",
    "expectedPaidCompositionFingerprint": "djb2:bf0ccb72",
    "expectedPaidEssenceFingerprint": "djb2:5f54c120",
    "contentSource": "TYPE_CATALOG+STEM_BODIES"
  },
  {
    "case_id": "DM-YR-1999-12-31",
    "birthDate": "1999-12-31",
    "birthTime": null,
    "birthTimeUnknown": true,
    "country": "JP",
    "timezone": "Asia/Tokyo",
    "stemLaneIndex": 9,
    "stemChar": "癸",
    "publicTitle": "アナリスト",
    "imagePath": "/ten-views/analyst.webp",
    "calculationMode": "unknown_time_noon",
    "errorCode": null,
    "certification_status": "REVIEW_REQUIRED",
    "expectedCoreLabel": "統合設計型",
    "expectedCoreType": "TYPE_10",
    "expectedCoreSummary": "バラバラの要素を一つの形にまとめ、全体として意味を持たせようとする本質です。統合と設計の観測が前に出やすいタイプです。",
    "expectedWorkStyleSummary": "バラバラの要素をひとつの流れにまとめ、全体の見通しが立つときに力を発揮しやすい観測です。",
    "expectedPaidIdentityFingerprint": "djb2:73559756",
    "expectedPaidCompositionFingerprint": "djb2:72fe3c33",
    "expectedPaidEssenceFingerprint": "djb2:3743edb9",
    "contentSource": "TYPE_CATALOG+STEM_BODIES"
  },
  {
    "case_id": "DM-YR-2000-01-01",
    "birthDate": "2000-01-01",
    "birthTime": null,
    "birthTimeUnknown": true,
    "country": "JP",
    "timezone": "Asia/Tokyo",
    "stemLaneIndex": 0,
    "stemChar": "甲",
    "publicTitle": "プレジデント",
    "imagePath": "/ten-views/president.webp",
    "calculationMode": "unknown_time_noon",
    "errorCode": null,
    "certification_status": "REVIEW_REQUIRED",
    "expectedCoreLabel": "観測深化型",
    "expectedCoreType": "TYPE_01",
    "expectedCoreSummary": "表面で終わらず、小さな差分や意味の層を拾い上げて深めようとする本質です。静かに精度を上げるタイプの観測です。",
    "expectedWorkStyleSummary": "ひとりで深く向き合える時間と、静かな余白があるときに力が出やすい観測です。割り込みが少ないほど輪郭がはっきりします。",
    "expectedPaidIdentityFingerprint": "djb2:76b981e0",
    "expectedPaidCompositionFingerprint": "djb2:88a1863b",
    "expectedPaidEssenceFingerprint": "djb2:4b548610",
    "contentSource": "TYPE_CATALOG+STEM_BODIES"
  },
  {
    "case_id": "DM-LEAP-2016-02-29",
    "birthDate": "2016-02-29",
    "birthTime": null,
    "birthTimeUnknown": true,
    "country": "JP",
    "timezone": "Asia/Tokyo",
    "stemLaneIndex": 3,
    "stemChar": "丁",
    "publicTitle": "クリエイター",
    "imagePath": "/ten-views/creator.webp",
    "calculationMode": "unknown_time_noon",
    "errorCode": null,
    "certification_status": "REVIEW_REQUIRED",
    "expectedCoreLabel": "静観分析型",
    "expectedCoreType": "TYPE_04",
    "expectedCoreSummary": "動きの前に観測を置き、状況を分解してから動こうとする本質です。静けさの中で精度を上げるタイプの観測です。",
    "expectedWorkStyleSummary": "静かに観察し、小さな変化から読み直せる時間があるときに力を発揮しやすいです。",
    "expectedPaidIdentityFingerprint": "djb2:d33fc8f2",
    "expectedPaidCompositionFingerprint": "djb2:c35207e7",
    "expectedPaidEssenceFingerprint": "djb2:364a9d71",
    "contentSource": "TYPE_CATALOG+STEM_BODIES"
  }
] as const;
