import type { DivinationGoldenMatrixCaseInput } from './divinationGoldenMatrixAudit';

/** ENGINE_VERIFY / pipeline.golden certified expectations only. */
export const DIVINATION_GOLDEN_MATRIX_CASES: DivinationGoldenMatrixCaseInput[] = [
  {
    case_id: 'DM-GX-01',
    certification_status: 'CERTIFIED',
    birthDate: '1983-02-28',
    birthTimeUnknown: true,
    country: 'JP',
    timezone: 'Asia/Tokyo',
    expected: {
      stemLaneIndex: 9,
      stemChar: '癸',
      publicTitle: 'アナリスト',
      displayOneLine: '小さな変化を拾い、深く読み解く人',
      imagePath: '/ten-views/analyst.webp',
      calculationMode: 'unknown_time_noon',
    },
    parity: {
      core_expected_title: 'クリエイター',
      locked_shelf_expected_title: 'アナリスト',
      dtr_snapshot_expected_title: 'N/A',
      visual_parity_expected: false,
    },
  },
  {
    case_id: 'DM-GX-01-noon',
    certification_status: 'CERTIFIED',
    birthDate: '1983-02-28',
    birthTime: '12:00',
    birthTimeUnknown: false,
    country: 'JP',
    timezone: 'Asia/Tokyo',
    birthplace: '東京都',
    expected: {
      stemLaneIndex: 9,
      stemChar: '癸',
      publicTitle: 'アナリスト',
      displayOneLine: '小さな変化を拾い、深く読み解く人',
      imagePath: '/ten-views/analyst.webp',
      calculationMode: 'full',
    },
    parity: {
      core_expected_title: 'クリエイター',
      locked_shelf_expected_title: 'アナリスト',
      dtr_snapshot_expected_title: 'N/A',
      visual_parity_expected: false,
    },
  },
  {
    case_id: 'DM-ADJ-1983-02-27',
    certification_status: 'REVIEW_REQUIRED',
    birthDate: '1983-02-27',
    birthTimeUnknown: true,
    country: 'JP',
  },
  {
    case_id: 'DM-ADJ-1983-03-01',
    certification_status: 'REVIEW_REQUIRED',
    birthDate: '1983-03-01',
    birthTimeUnknown: true,
    country: 'JP',
  },
  {
    case_id: 'DM-SOL-2024-02-03',
    certification_status: 'CERTIFIED',
    birthDate: '2024-02-03',
    birthTime: '12:00',
    birthTimeUnknown: false,
    country: 'JP',
    expected: {
      stemLaneIndex: 9,
      stemChar: '癸',
      publicTitle: 'アナリスト',
      imagePath: '/ten-views/analyst.webp',
      calculationMode: 'full',
    },
  },
  {
    case_id: 'DM-SOL-2024-02-04',
    certification_status: 'CERTIFIED',
    birthDate: '2024-02-04',
    birthTime: '12:00',
    birthTimeUnknown: false,
    country: 'JP',
    expected: {
      stemLaneIndex: 0,
      stemChar: '甲',
      publicTitle: 'プレジデント',
      imagePath: '/ten-views/president.webp',
      calculationMode: 'full',
    },
  },
  {
    case_id: 'DM-SOL-2024-02-05',
    certification_status: 'CERTIFIED',
    birthDate: '2024-02-05',
    birthTime: '12:00',
    birthTimeUnknown: false,
    country: 'JP',
    expected: {
      stemLaneIndex: 1,
      stemChar: '乙',
      publicTitle: 'プランナー',
      imagePath: '/ten-views/planner.webp',
      calculationMode: 'full',
    },
  },
  {
    case_id: 'DM-LUN-2024-01-11',
    certification_status: 'CERTIFIED',
    birthDate: '2024-01-11',
    birthTime: '12:00',
    birthTimeUnknown: false,
    country: 'JP',
    expected: {
      stemLaneIndex: 6,
      stemChar: '庚',
      publicTitle: 'エグゼキューター',
      imagePath: '/ten-views/executor.webp',
      calculationMode: 'full',
    },
  },
  {
    case_id: 'DM-LUN-2024-02-10',
    certification_status: 'CERTIFIED',
    birthDate: '2024-02-10',
    birthTime: '12:00',
    birthTimeUnknown: false,
    country: 'JP',
    expected: {
      stemLaneIndex: 6,
      stemChar: '庚',
      publicTitle: 'エグゼキューター',
      imagePath: '/ten-views/executor.webp',
      calculationMode: 'full',
    },
  },
  {
    case_id: 'DM-YR-1999-12-31',
    certification_status: 'REVIEW_REQUIRED',
    birthDate: '1999-12-31',
    birthTimeUnknown: true,
    country: 'JP',
  },
  {
    case_id: 'DM-YR-2000-01-01',
    certification_status: 'REVIEW_REQUIRED',
    birthDate: '2000-01-01',
    birthTimeUnknown: true,
    country: 'JP',
  },
  {
    case_id: 'DM-LEAP-2016-02-29',
    certification_status: 'REVIEW_REQUIRED',
    birthDate: '2016-02-29',
    birthTimeUnknown: true,
    country: 'JP',
  },
  {
    case_id: 'DM-TIME-unknown-noon',
    certification_status: 'CERTIFIED',
    birthDate: '1983-02-28',
    birthTimeUnknown: true,
    country: 'JP',
    timezone: 'Asia/Tokyo',
    expected: {
      stemLaneIndex: 9,
      stemChar: '癸',
      publicTitle: 'アナリスト',
      imagePath: '/ten-views/analyst.webp',
      calculationMode: 'unknown_time_noon',
    },
  },
  {
    case_id: 'DM-TIME-explicit-noon',
    certification_status: 'REVIEW_REQUIRED',
    birthDate: '1990-06-15',
    birthTime: '12:00',
    birthTimeUnknown: false,
    country: 'JP',
  },
  {
    case_id: 'DM-TIME-2330',
    certification_status: 'INVARIANT_ONLY',
    birthDate: '1983-02-28',
    birthTime: '23:30',
    birthTimeUnknown: false,
    country: 'JP',
    timezone: 'Asia/Tokyo',
    invariants: {
      effectiveLocalDate: '1983-03-01',
      stemDiffersFromNoonReference: true,
    },
  },
  {
    case_id: 'DM-TIME-0330',
    certification_status: 'CERTIFIED',
    birthDate: '1990-06-15',
    birthTime: '03:30',
    birthTimeUnknown: false,
    country: 'JP',
    expected: {
      stemLaneIndex: 3,
      stemChar: '丁',
      publicTitle: 'クリエイター',
      imagePath: '/ten-views/creator.webp',
      calculationMode: 'full',
    },
  },
  {
    case_id: 'DM-INV-no-legacy-lane',
    certification_status: 'INVARIANT_ONLY',
    birthDate: '1983-02-28',
    birthTime: '12:00',
    birthTimeUnknown: false,
    country: 'JP',
    invariants: { noLegacyLane: true },
  },
  {
    case_id: 'DM-INV-boundary-present',
    certification_status: 'INVARIANT_ONLY',
    birthDate: '1983-02-28',
    birthTimeUnknown: true,
    country: 'JP',
    invariants: { boundaryPresent: true },
  },
  {
    case_id: 'DM-INV-incomplete-profile',
    certification_status: 'INVARIANT_ONLY',
    birthDate: '1983-02-28',
    birthTimeUnknown: false,
    country: 'JP',
    invariants: { incompleteProfile: true },
  },
];
