/**
 * M55 Experience Control Plane v2 — complete user-visible route/surface registry.
 * A governed surface missing from this registry fails verification.
 */

import type { M55ExperienceArchetype, ExperiencePrintMode } from './experienceArchetypes';
import type { M55CtaState } from './experienceCtaState';
import { assetKeysForRoute } from '../assetLedger/assetRouteConsumption';

export type ExperienceShellId = 'public' | 'core' | 'reader' | 'clerk';
export type ExperienceHeaderMode = 'full_public' | 'contextual_public' | 'clerk' | 'none';
export type ExperienceFooterMode = 'quiet_public' | 'minimal' | 'none';
export type ExperiencePrivacyClass =
  | 'public'
  | 'privacy_safe_share'
  | 'guest_session'
  | 'authenticated'
  | 'purchased_private'
  | 'legal_public';
export type ExperienceMigrationClass =
  | 'ecp_v2_active'
  | 'quiet_disabled'
  | 'legacy_adjacent'
  | 'dev_only'
  | 'prototype_gated';

export type ExperienceProductTruthDeps =
  | 'none'
  | 'self_premium_prices'
  | 'plan_comparison'
  | 'trait_identity'
  | 'legal_copy';

export type ExperienceRouteEntry = {
  id: string;
  /** Explicit path or typed pattern (e.g. /r/:token). */
  pattern: string;
  state?: string;
  archetype: M55ExperienceArchetype;
  shell: ExperienceShellId;
  primaryCtaState: M55CtaState | 'CONTEXTUAL' | 'NONE';
  headerMode: ExperienceHeaderMode;
  footerMode: ExperienceFooterMode;
  printMode: ExperiencePrintMode;
  privacy: ExperiencePrivacyClass;
  productTruth: ExperienceProductTruthDeps;
  migration: ExperienceMigrationClass;
  ownerFiles: readonly string[];
};

export const M55_EXPERIENCE_ROUTE_REGISTRY: readonly ExperienceRouteEntry[] = [
  // PUBLIC
  {
    id: 'public.home',
    pattern: '/home',
    archetype: 'PUBLIC_POSTER',
    shell: 'public',
    primaryCtaState: 'CONTEXTUAL',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'brochure_2page',
    privacy: 'public',
    productTruth: 'plan_comparison',
    migration: 'ecp_v2_active',
    ownerFiles: ['app/home/page.tsx', 'components/home/HomePanel.tsx'],
  },
  {
    id: 'public.root_redirect',
    pattern: '/',
    archetype: 'PUBLIC_POSTER',
    shell: 'public',
    primaryCtaState: 'FRESH',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'brochure_2page',
    privacy: 'public',
    productTruth: 'none',
    migration: 'ecp_v2_active',
    ownerFiles: ['app/page.tsx'],
  },
  {
    id: 'public.how_m55_works',
    pattern: '/how-m55-works',
    archetype: 'PUBLIC_EDITORIAL',
    shell: 'public',
    primaryCtaState: 'FRESH',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'editorial_result',
    privacy: 'public',
    productTruth: 'none',
    migration: 'ecp_v2_active',
    ownerFiles: ['app/how-m55-works/page.tsx'],
  },
  {
    id: 'public.ten_views',
    pattern: '/ten-views',
    archetype: 'PUBLIC_EDITORIAL',
    shell: 'public',
    primaryCtaState: 'FRESH',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'editorial_result',
    privacy: 'public',
    productTruth: 'trait_identity',
    migration: 'ecp_v2_active',
    ownerFiles: ['app/ten-views/page.tsx', 'components/pages/M55TenViews.tsx'],
  },
  {
    id: 'public.pricing',
    pattern: '/pricing',
    archetype: 'PRODUCT_DECISION',
    shell: 'public',
    primaryCtaState: 'PREMIUM_COMPLETE',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'product_fact',
    privacy: 'public',
    productTruth: 'self_premium_prices',
    migration: 'ecp_v2_active',
    ownerFiles: ['app/pricing/page.tsx'],
  },
  {
    id: 'public.support',
    pattern: '/support',
    archetype: 'PUBLIC_EDITORIAL',
    shell: 'public',
    primaryCtaState: 'NONE',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'editorial_result',
    privacy: 'legal_public',
    productTruth: 'legal_copy',
    migration: 'ecp_v2_active',
    ownerFiles: ['app/support/page.tsx'],
  },
  {
    id: 'public.legal.terms',
    pattern: '/legal/terms',
    archetype: 'PUBLIC_EDITORIAL',
    shell: 'public',
    primaryCtaState: 'NONE',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'editorial_result',
    privacy: 'legal_public',
    productTruth: 'legal_copy',
    migration: 'ecp_v2_active',
    ownerFiles: ['app/legal/terms/page.tsx'],
  },
  {
    id: 'public.legal.privacy',
    pattern: '/legal/privacy',
    archetype: 'PUBLIC_EDITORIAL',
    shell: 'public',
    primaryCtaState: 'NONE',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'editorial_result',
    privacy: 'legal_public',
    productTruth: 'legal_copy',
    migration: 'ecp_v2_active',
    ownerFiles: ['app/legal/privacy/page.tsx'],
  },
  {
    id: 'public.legal.tokushoho',
    pattern: '/legal/tokushoho',
    archetype: 'PUBLIC_EDITORIAL',
    shell: 'public',
    primaryCtaState: 'NONE',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'editorial_result',
    privacy: 'legal_public',
    productTruth: 'legal_copy',
    migration: 'ecp_v2_active',
    ownerFiles: ['app/legal/tokushoho/page.tsx'],
  },
  {
    id: 'public.legal.refund',
    pattern: '/legal/refund',
    archetype: 'PUBLIC_EDITORIAL',
    shell: 'public',
    primaryCtaState: 'NONE',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'editorial_result',
    privacy: 'legal_public',
    productTruth: 'legal_copy',
    migration: 'ecp_v2_active',
    ownerFiles: ['app/legal/refund/page.tsx'],
  },
  {
    id: 'public.sign_in',
    pattern: '/sign-in',
    state: 'login_entry',
    archetype: 'PUBLIC_EDITORIAL',
    shell: 'clerk',
    primaryCtaState: 'NONE',
    headerMode: 'clerk',
    footerMode: 'none',
    printMode: 'single_summary',
    privacy: 'authenticated',
    productTruth: 'none',
    migration: 'ecp_v2_active',
    ownerFiles: ['app/sign-in/[[...sign-in]]/page.tsx'],
  },
  {
    id: 'public.sign_up',
    pattern: '/sign-up',
    state: 'login_entry',
    archetype: 'PUBLIC_EDITORIAL',
    shell: 'clerk',
    primaryCtaState: 'NONE',
    headerMode: 'clerk',
    footerMode: 'none',
    printMode: 'single_summary',
    privacy: 'authenticated',
    productTruth: 'none',
    migration: 'ecp_v2_active',
    ownerFiles: ['app/sign-up/[[...sign-up]]/page.tsx'],
  },
  {
    id: 'public.my',
    pattern: '/my',
    state: 'account_menu',
    archetype: 'PUBLIC_EDITORIAL',
    shell: 'core',
    primaryCtaState: 'CONTEXTUAL',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'single_summary',
    privacy: 'authenticated',
    productTruth: 'none',
    migration: 'ecp_v2_active',
    ownerFiles: ['app/my/page.tsx'],
  },

  // FREE
  {
    id: 'free.core.empty',
    pattern: '/core',
    state: 'empty',
    archetype: 'GUIDED_FREE_FLOW',
    shell: 'core',
    primaryCtaState: 'FRESH',
    headerMode: 'contextual_public',
    footerMode: 'quiet_public',
    printMode: 'single_summary',
    privacy: 'guest_session',
    productTruth: 'none',
    migration: 'ecp_v2_active',
    ownerFiles: ['app/core/page.tsx', 'components/core/CoreLockedState.tsx'],
  },
  {
    id: 'free.core.intake',
    pattern: '/core',
    state: 'intake',
    archetype: 'GUIDED_FREE_FLOW',
    shell: 'core',
    primaryCtaState: 'FRESH',
    headerMode: 'contextual_public',
    footerMode: 'quiet_public',
    printMode: 'single_summary',
    privacy: 'guest_session',
    productTruth: 'none',
    migration: 'ecp_v2_active',
    ownerFiles: ['components/profile/BirthProfileIntakeLayer.tsx'],
  },
  {
    id: 'free.core.questions',
    pattern: '/core',
    state: 'free_questions',
    archetype: 'GUIDED_FREE_FLOW',
    shell: 'core',
    primaryCtaState: 'FREE_IN_PROGRESS',
    headerMode: 'contextual_public',
    footerMode: 'quiet_public',
    printMode: 'single_summary',
    privacy: 'guest_session',
    productTruth: 'none',
    migration: 'ecp_v2_active',
    ownerFiles: ['components/core/CoreFreeQuestionnaireLayer.tsx'],
  },
  {
    id: 'free.core.answer_review',
    pattern: '/core',
    state: 'answer_review',
    archetype: 'GUIDED_FREE_FLOW',
    shell: 'core',
    primaryCtaState: 'FREE_IN_PROGRESS',
    headerMode: 'contextual_public',
    footerMode: 'quiet_public',
    printMode: 'single_summary',
    privacy: 'guest_session',
    productTruth: 'none',
    migration: 'ecp_v2_active',
    ownerFiles: ['components/core/CoreEssencePanel.tsx'],
  },
  {
    id: 'free.core.result',
    pattern: '/core',
    state: 'result',
    archetype: 'EDITORIAL_FREE_RESULT',
    shell: 'core',
    primaryCtaState: 'FREE_TO_PREMIUM',
    headerMode: 'contextual_public',
    footerMode: 'quiet_public',
    printMode: 'editorial_result',
    privacy: 'guest_session',
    productTruth: 'trait_identity',
    migration: 'ecp_v2_active',
    ownerFiles: ['components/core/CoreEssencePanel.tsx', 'components/core/CorePremiumStickyCta.tsx'],
  },
  {
    id: 'free.core.save',
    pattern: '/core',
    state: 'save',
    archetype: 'EDITORIAL_FREE_RESULT',
    shell: 'core',
    primaryCtaState: 'FREE_COMPLETE',
    headerMode: 'contextual_public',
    footerMode: 'quiet_public',
    printMode: 'editorial_result',
    privacy: 'guest_session',
    productTruth: 'trait_identity',
    migration: 'ecp_v2_active',
    ownerFiles: ['lib/m55/freeResult/guestFreeJourneyCopyV1.ts'],
  },
  {
    id: 'free.core.rerun',
    pattern: '/core',
    state: 'rerun',
    archetype: 'EDITORIAL_FREE_RESULT',
    shell: 'core',
    primaryCtaState: 'FREE_COMPLETE',
    headerMode: 'contextual_public',
    footerMode: 'quiet_public',
    printMode: 'editorial_result',
    privacy: 'guest_session',
    productTruth: 'trait_identity',
    migration: 'ecp_v2_active',
    ownerFiles: ['lib/m55/selfFunnel/selfFunnelRuntimeState.ts'],
  },
  {
    id: 'free.core.share',
    pattern: '/core',
    state: 'share',
    archetype: 'EDITORIAL_FREE_RESULT',
    shell: 'core',
    primaryCtaState: 'FREE_TO_PREMIUM',
    headerMode: 'contextual_public',
    footerMode: 'quiet_public',
    printMode: 'privacy_safe',
    privacy: 'privacy_safe_share',
    productTruth: 'trait_identity',
    migration: 'ecp_v2_active',
    ownerFiles: ['lib/m55/freeResult/privacySafeShareCardV1.ts'],
  },

  // SHARED
  {
    id: 'shared.entry',
    pattern: '/r/:token',
    archetype: 'SHARED_SOCIAL_ENTRY',
    shell: 'public',
    primaryCtaState: 'SHARED_RECIPIENT',
    headerMode: 'contextual_public',
    footerMode: 'quiet_public',
    printMode: 'privacy_safe',
    privacy: 'privacy_safe_share',
    productTruth: 'trait_identity',
    migration: 'ecp_v2_active',
    ownerFiles: ['app/r/[token]/page.tsx', 'components/share/SharedEntryPanel.tsx'],
  },
  {
    id: 'shared.entry.invalid',
    pattern: '/r/:token',
    state: 'invalid',
    archetype: 'SHARED_SOCIAL_ENTRY',
    shell: 'public',
    primaryCtaState: 'SHARED_RECIPIENT',
    headerMode: 'contextual_public',
    footerMode: 'quiet_public',
    printMode: 'privacy_safe',
    privacy: 'privacy_safe_share',
    productTruth: 'none',
    migration: 'ecp_v2_active',
    ownerFiles: ['components/share/SharedEntryPanel.tsx'],
  },
  {
    id: 'shared.og',
    pattern: '/r/:token/opengraph-image',
    state: 'og',
    archetype: 'SHARED_SOCIAL_ENTRY',
    shell: 'public',
    primaryCtaState: 'NONE',
    headerMode: 'none',
    footerMode: 'none',
    printMode: 'privacy_safe',
    privacy: 'privacy_safe_share',
    productTruth: 'trait_identity',
    migration: 'ecp_v2_active',
    ownerFiles: ['app/r/[token]/opengraph-image.tsx'],
  },

  // PREMIUM
  {
    id: 'premium.dtr_index',
    pattern: '/dtr',
    archetype: 'DIGITAL_PUBLICATION',
    shell: 'public',
    primaryCtaState: 'CONTEXTUAL',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'editorial_result',
    privacy: 'public',
    productTruth: 'plan_comparison',
    migration: 'ecp_v2_active',
    ownerFiles: ['app/dtr/page.tsx'],
  },
  {
    id: 'premium.lp.intro',
    pattern: '/dtr/lp',
    state: 'introduction',
    archetype: 'PRODUCT_DECISION',
    shell: 'public',
    primaryCtaState: 'FREE_TO_PREMIUM',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'product_fact',
    privacy: 'public',
    productTruth: 'plan_comparison',
    migration: 'ecp_v2_active',
    ownerFiles: ['app/dtr/lp/page.tsx', 'components/dtr/DtrLpPremiumContinuityIntro.tsx'],
  },
  {
    id: 'premium.lp.need_free',
    pattern: '/dtr/lp',
    state: 'need_free',
    archetype: 'PRODUCT_DECISION',
    shell: 'public',
    primaryCtaState: 'FRESH',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'product_fact',
    privacy: 'guest_session',
    productTruth: 'none',
    migration: 'ecp_v2_active',
    ownerFiles: ['components/dtr/DtrNeedFreeResultGate.tsx'],
  },
  {
    id: 'premium.lp.questions',
    pattern: '/dtr/lp',
    state: 'six_questions',
    archetype: 'PREMIUM_GUIDED_FLOW',
    shell: 'public',
    primaryCtaState: 'PREMIUM_IN_PROGRESS',
    headerMode: 'contextual_public',
    footerMode: 'quiet_public',
    printMode: 'product_fact',
    privacy: 'guest_session',
    productTruth: 'trait_identity',
    migration: 'ecp_v2_active',
    ownerFiles: ['components/dtr/DtrPaidPurchasePrep.tsx'],
  },
  {
    id: 'premium.lp.answer_review',
    pattern: '/dtr/lp',
    state: 'answer_review',
    archetype: 'PREMIUM_GUIDED_FLOW',
    shell: 'public',
    primaryCtaState: 'PREMIUM_COMPLETE',
    headerMode: 'contextual_public',
    footerMode: 'quiet_public',
    printMode: 'product_fact',
    privacy: 'guest_session',
    productTruth: 'trait_identity',
    migration: 'ecp_v2_active',
    ownerFiles: ['components/dtr/DtrPaidPurchasePrep.tsx'],
  },
  {
    id: 'premium.lp.plans',
    pattern: '/dtr/lp',
    state: 'plan_selection',
    archetype: 'PRODUCT_DECISION',
    shell: 'public',
    primaryCtaState: 'PREMIUM_COMPLETE',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'product_fact',
    privacy: 'guest_session',
    productTruth: 'self_premium_prices',
    migration: 'ecp_v2_active',
    ownerFiles: ['components/dtr/DtrPaidPurchasePrep.tsx', 'lib/m55/commercialUx/planComparison.ts'],
  },
  {
    id: 'premium.lp.upgrade',
    pattern: '/dtr/lp',
    state: 'upgrade_explanation',
    archetype: 'PRODUCT_DECISION',
    shell: 'public',
    primaryCtaState: 'PLAN_SELECTED',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'product_fact',
    privacy: 'guest_session',
    productTruth: 'self_premium_prices',
    migration: 'ecp_v2_active',
    ownerFiles: ['lib/m55/commercialUx/planComparison.ts'],
  },
  {
    id: 'premium.lp.checkout',
    pattern: '/dtr/lp',
    state: 'payment_preparation',
    archetype: 'PURCHASE_CONFIRMATION',
    shell: 'public',
    primaryCtaState: 'PAYMENT_READY',
    headerMode: 'contextual_public',
    footerMode: 'minimal',
    printMode: 'product_fact',
    privacy: 'guest_session',
    productTruth: 'self_premium_prices',
    migration: 'ecp_v2_active',
    ownerFiles: ['components/dtr/DtrPaidPurchasePrep.tsx'],
  },
  {
    id: 'premium.processing',
    pattern: '/dtr/processing',
    archetype: 'PURCHASE_CONFIRMATION',
    shell: 'public',
    primaryCtaState: 'PURCHASED',
    headerMode: 'contextual_public',
    footerMode: 'minimal',
    printMode: 'product_fact',
    privacy: 'purchased_private',
    productTruth: 'none',
    migration: 'ecp_v2_active',
    ownerFiles: ['app/dtr/processing/page.tsx'],
  },
  {
    id: 'premium.purchase_success',
    pattern: '/purchase/success',
    archetype: 'PURCHASE_CONFIRMATION',
    shell: 'public',
    primaryCtaState: 'PURCHASED',
    headerMode: 'contextual_public',
    footerMode: 'minimal',
    printMode: 'product_fact',
    privacy: 'purchased_private',
    productTruth: 'none',
    migration: 'ecp_v2_active',
    ownerFiles: ['app/purchase/success/page.tsx'],
  },

  // PURCHASED
  {
    id: 'purchased.reader',
    pattern: '/dtr/core',
    archetype: 'DIGITAL_PUBLICATION',
    shell: 'reader',
    primaryCtaState: 'PURCHASED',
    headerMode: 'contextual_public',
    footerMode: 'minimal',
    printMode: 'editorial_result',
    privacy: 'purchased_private',
    productTruth: 'none',
    migration: 'ecp_v2_active',
    ownerFiles: ['app/dtr/core/page.tsx', 'app/dtr/core/layout.tsx'],
  },

  // QUIET / LEGACY (registered, not Growth active)
  {
    id: 'legacy.tarot',
    pattern: '/tarot',
    archetype: 'PUBLIC_EDITORIAL',
    shell: 'core',
    primaryCtaState: 'NONE',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'single_summary',
    privacy: 'public',
    productTruth: 'none',
    migration: 'quiet_disabled',
    ownerFiles: ['app/tarot/page.tsx'],
  },
  {
    id: 'legacy.ai_chat',
    pattern: '/ai-chat',
    archetype: 'PUBLIC_EDITORIAL',
    shell: 'core',
    primaryCtaState: 'NONE',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'single_summary',
    privacy: 'public',
    productTruth: 'none',
    migration: 'quiet_disabled',
    ownerFiles: ['app/ai-chat/page.tsx'],
  },
  {
    id: 'legacy.today',
    pattern: '/today',
    archetype: 'PUBLIC_EDITORIAL',
    shell: 'core',
    primaryCtaState: 'NONE',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'single_summary',
    privacy: 'public',
    productTruth: 'none',
    migration: 'legacy_adjacent',
    ownerFiles: ['app/today/page.tsx'],
  },
  {
    id: 'legacy.weekly',
    pattern: '/weekly',
    archetype: 'PUBLIC_EDITORIAL',
    shell: 'core',
    primaryCtaState: 'NONE',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'single_summary',
    privacy: 'public',
    productTruth: 'none',
    migration: 'legacy_adjacent',
    ownerFiles: ['app/weekly/page.tsx'],
  },
  {
    id: 'legacy.calendar',
    pattern: '/calendar',
    archetype: 'PUBLIC_EDITORIAL',
    shell: 'core',
    primaryCtaState: 'NONE',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'single_summary',
    privacy: 'public',
    productTruth: 'none',
    migration: 'legacy_adjacent',
    ownerFiles: ['app/calendar/page.tsx'],
  },
  {
    id: 'legacy.ai_calendar',
    pattern: '/ai-calendar',
    archetype: 'PUBLIC_EDITORIAL',
    shell: 'core',
    primaryCtaState: 'NONE',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'single_summary',
    privacy: 'public',
    productTruth: 'none',
    migration: 'legacy_adjacent',
    ownerFiles: ['app/ai-calendar/page.tsx'],
  },
  {
    id: 'legacy.meter',
    pattern: '/meter',
    archetype: 'PUBLIC_EDITORIAL',
    shell: 'core',
    primaryCtaState: 'NONE',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'single_summary',
    privacy: 'public',
    productTruth: 'none',
    migration: 'legacy_adjacent',
    ownerFiles: ['app/meter/page.tsx'],
  },
  {
    id: 'legacy.reply',
    pattern: '/reply',
    archetype: 'PUBLIC_EDITORIAL',
    shell: 'public',
    primaryCtaState: 'NONE',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'single_summary',
    privacy: 'public',
    productTruth: 'none',
    migration: 'legacy_adjacent',
    ownerFiles: ['app/reply/page.tsx'],
  },
  {
    id: 'legacy.reply_result',
    pattern: '/reply/result',
    archetype: 'PUBLIC_EDITORIAL',
    shell: 'public',
    primaryCtaState: 'NONE',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'single_summary',
    privacy: 'public',
    productTruth: 'none',
    migration: 'legacy_adjacent',
    ownerFiles: ['app/reply/result/page.tsx'],
  },
  {
    id: 'legacy.synastry',
    pattern: '/synastry',
    archetype: 'PRODUCT_DECISION',
    shell: 'public',
    primaryCtaState: 'NONE',
    headerMode: 'full_public',
    footerMode: 'quiet_public',
    printMode: 'product_fact',
    privacy: 'public',
    productTruth: 'none',
    migration: 'legacy_adjacent',
    ownerFiles: ['app/synastry/page.tsx'],
  },
  {
    id: 'legacy.synastry.confirm',
    pattern: '/synastry/purchase/confirm',
    archetype: 'PURCHASE_CONFIRMATION',
    shell: 'public',
    primaryCtaState: 'PAYMENT_READY',
    headerMode: 'contextual_public',
    footerMode: 'minimal',
    printMode: 'product_fact',
    privacy: 'guest_session',
    productTruth: 'none',
    migration: 'legacy_adjacent',
    ownerFiles: ['app/synastry/purchase/confirm/page.tsx'],
  },
  {
    id: 'legacy.synastry.success',
    pattern: '/synastry/purchase/success',
    archetype: 'PURCHASE_CONFIRMATION',
    shell: 'public',
    primaryCtaState: 'PURCHASED',
    headerMode: 'contextual_public',
    footerMode: 'minimal',
    printMode: 'product_fact',
    privacy: 'purchased_private',
    productTruth: 'none',
    migration: 'legacy_adjacent',
    ownerFiles: ['app/synastry/purchase/success/page.tsx'],
  },
  {
    id: 'legacy.synastry.report',
    pattern: '/synastry/report/:reportId',
    archetype: 'DIGITAL_PUBLICATION',
    shell: 'public',
    primaryCtaState: 'NONE',
    headerMode: 'contextual_public',
    footerMode: 'minimal',
    printMode: 'editorial_result',
    privacy: 'purchased_private',
    productTruth: 'none',
    migration: 'legacy_adjacent',
    ownerFiles: ['app/synastry/report/[reportId]/page.tsx'],
  },
  {
    id: 'prototype.hub',
    pattern: '/prototype',
    archetype: 'PUBLIC_EDITORIAL',
    shell: 'public',
    primaryCtaState: 'NONE',
    headerMode: 'none',
    footerMode: 'none',
    printMode: 'single_summary',
    privacy: 'public',
    productTruth: 'none',
    migration: 'prototype_gated',
    ownerFiles: ['app/prototype/page.tsx'],
  },
  {
    id: 'dev.previews',
    pattern: '/dev/:slug',
    archetype: 'PUBLIC_EDITORIAL',
    shell: 'public',
    primaryCtaState: 'NONE',
    headerMode: 'none',
    footerMode: 'none',
    printMode: 'single_summary',
    privacy: 'public',
    productTruth: 'none',
    migration: 'dev_only',
    ownerFiles: ['app/dev'],
  },
] as const;

export function listRegistryPatterns(): string[] {
  return [...new Set(M55_EXPERIENCE_ROUTE_REGISTRY.map((e) => e.pattern))];
}

export function registryEntryById(id: string): ExperienceRouteEntry | undefined {
  return M55_EXPERIENCE_ROUTE_REGISTRY.find((e) => e.id === id);
}

/** Asset keys consumed by a governed route — from asset-first SSOT consumption map. */
export function resolveRouteAssetKeys(routeId: string): readonly string[] {
  return assetKeysForRoute(routeId);
}

export function assertRouteAssetConsumptionComplete(): void {
  for (const entry of M55_EXPERIENCE_ROUTE_REGISTRY) {
    const keys = assetKeysForRoute(entry.id);
    if (keys.length === 0) {
      throw new Error(`route missing asset consumption: ${entry.id}`);
    }
  }
}
