import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import { canonicalPathIdentity, exitCodeForStatus, htmlEscape, parseWorktrees, redactRemote, resolveGitExecutable, safeRead, stableJson, validateAuthorityPath } from './engine.mjs';
import { AUTHORITY_MANIFEST, inspectM55 } from './m55-adapter.mjs';
import { inspectNebula } from './examples/nebula-adapter.mjs';
import { agentBootstrap, handoffMarkdown, renderHtml } from './packet.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const ACTION = 'Human selection of Self Funnel visual direction, result length, and ten-asset presentation. No source implementation is authorized before that selection.';

function fixture(mutator = () => {}) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'm55 handoff-'));
  const content = {
    'AGENTS.md': 'agent', 'docs/ssot/README.md': 'readme', 'docs/ssot/M55_COMMERCIAL_FUNNEL_SSOT.md': 'ssot', 'docs/ssot/M55_DECISION_LOG.md': 'log', 'docs/ssot/M55_ROADMAP.md': '1. Commercial Funnel SSOT',
    'docs/ssot/M55_CURRENT_STATE.md': `CLOSED_GREEN\n| **postMergeNextSingleAction** | ${ACTION} |\n\n### Prohibited ahead of Self funnel\n\n- implementation while authority is unresolved\n\n## Active session`,
    'docs/ssot/M55_WORKTREE_REGISTRY.md': 'Documented post-merge transition\n### WT-001 — fixture\n| Field | Value |\n|---|---|\n| path | `/fixture` |\n| branch | `main` |\n| lifecycle | **ACTIVE** + **PRIMARY_MAIN_HOME** (designation) |\n---',
    'docs/ssot/M55_SELF_FUNNEL_CONTRACT.md': '## Target flow\n## Current runtime (NOT target)\nNOT_YET_IMPLEMENTED\nno cross-device persistence guarantee\nno new Pair link',
    'lib/m55/contracts/m55CommercialFunnelContract.ts': "M55_CURRENT_RUNTIME_STATE\npreResultThemeSelection: true\nM55_TARGET_COMMERCIAL_CONTRACT\npreResultThemeSelection: false\nM55_DEFERRED_RUNTIME_ASSERTIONS\nACTIVE_LANE: '個人無料→個人Premiumファネルの一括実装'",
  };
  for (const rel of AUTHORITY_MANIFEST) { const file = path.join(root, rel); fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, content[rel]); }
  mutator(root);
  return root;
}
function identity(root, extra = {}) { return { root, branch: 'main', head: 'a', originMain: 'a', upstream: 'origin/main', remote: '', clean: true, dirtyFiles: 0, gitOperation: 'none', worktrees: [{ path: '/fixture', branch: 'main', head: 'a', detached: false }], ...extra }; }
function inspect(root, extra) { try { return inspectM55(root, identity(root, extra)); } finally { fs.rmSync(root, { recursive: true, force: true }); } }
function replace(root, rel, from, to) { const file = path.join(root, rel); fs.writeFileSync(file, fs.readFileSync(file, 'utf8').replace(from, to)); }
function gitFixture() {
  const root = fixture((dir) => replace(dir, 'docs/ssot/M55_WORKTREE_REGISTRY.md', '/fixture', fs.realpathSync(dir)));
  execFileSync('git', ['init', '--quiet', '--initial-branch=main'], { cwd: root });
  execFileSync('git', ['config', 'user.email', 'fixture@example.invalid'], { cwd: root });
  execFileSync('git', ['config', 'user.name', 'Fixture'], { cwd: root });
  execFileSync('git', ['add', '.'], { cwd: root });
  execFileSync('git', ['commit', '--quiet', '-m', 'fixture'], { cwd: root });
  execFileSync('git', ['remote', 'add', 'origin', 'https://token-like-secret@example.invalid/m55.git'], { cwd: root });
  execFileSync('git', ['update-ref', 'refs/remotes/origin/main', 'HEAD'], { cwd: root });
  return root;
}

test('01 clean registered repository → READY', () => assert.equal(inspect(fixture()).status, 'READY'));
test('02 clean explained stale snapshot → READY_WITH_WARNINGS', () => { const home = path.join(os.tmpdir(), 'M55_WORKTREE-home-final-ia-v1'); const root = fixture((dir) => { const registry = path.join(dir, 'docs/ssot/M55_WORKTREE_REGISTRY.md'); fs.writeFileSync(registry, fs.readFileSync(registry, 'utf8').replace('`main`', '`snapshot-branch`').replace('/fixture', home)); }); const report = inspect(root, { worktrees: [{ path: home, branch: 'main' }] }); assert.equal(report.status, 'READY_WITH_WARNINGS'); assert.ok(report.reasonCodes.includes('WORKTREE_DOCUMENTED_TRANSITION')); });
test('03 documented post-merge transition is warning only', () => { const home = path.join(os.tmpdir(), 'M55_WORKTREE-home-final-ia-v1'); const root = fixture((dir) => { const registry = path.join(dir, 'docs/ssot/M55_WORKTREE_REGISTRY.md'); fs.writeFileSync(registry, fs.readFileSync(registry, 'utf8').replace('`main`', '`old-branch`').replace('/fixture', home)); }); const report = inspect(root, { worktrees: [{ path: home, branch: 'main' }] }); assert.equal(report.status, 'READY_WITH_WARNINGS'); });
for (const [name, extra] of [['04 dirty tracked → HOLD/GIT_DIRTY', { clean: false, dirtyFiles: 1 }], ['05 staged → HOLD/GIT_DIRTY', { clean: false, dirtyFiles: 1 }], ['06 untracked → HOLD/GIT_DIRTY', { clean: false, dirtyFiles: 1 }]]) test(name, () => { const report = inspect(fixture(), extra); assert.equal(report.status, 'HOLD'); assert.ok(report.reasonCodes.includes('GIT_DIRTY')); });
for (const operation of ['merge', 'rebase', 'cherry-pick']) test(`07 active ${operation} → HOLD`, () => assert.equal(inspect(fixture(), { gitOperation: operation }).status, 'HOLD'));
test('08 missing authority → HOLD', () => { const root = fixture((dir) => fs.rmSync(path.join(dir, 'docs/ssot/M55_DECISION_LOG.md'))); assert.equal(inspect(root).status, 'HOLD'); });
test('09 malformed authority heading → HOLD', () => { const root = fixture((dir) => replace(dir, 'docs/ssot/M55_SELF_FUNNEL_CONTRACT.md', '## Target flow', '## Unknown')); assert.equal(inspect(root).status, 'HOLD'); });
test('10 unregistered live worktree → one stable HOLD finding', () => { const report = inspect(fixture(), { worktrees: [{ path: '/synthetic/unregistered', branch: 'main' }] }); assert.equal(report.status, 'HOLD'); assert.equal(report.checks.filter((item) => item.id === 'worktree:unregistered').length, 1); assert.equal(report.reasonCodes.filter((code) => code === 'WORKTREE_UNREGISTERED').length, 1); });
test('11 registered DO_NOT_USE worktree → WORKTREE_PROHIBITED only', () => { const root = fixture((dir) => replace(dir, 'docs/ssot/M55_WORKTREE_REGISTRY.md', '**ACTIVE** + **PRIMARY_MAIN_HOME** (designation)', '**DO_NOT_USE**')); const report = inspect(root); assert.equal(report.status, 'HOLD'); assert.deepEqual(report.reasonCodes, ['WORKTREE_PROHIBITED']); });
test('12 unexplained branch mismatch → HOLD', () => assert.equal(inspect(fixture(), { worktrees: [{ path: '/fixture', branch: 'other' }] }).status, 'HOLD'));
test('13 current/target swapped → HOLD', () => { const root = fixture((dir) => { const file = path.join(dir, 'lib/m55/contracts/m55CommercialFunnelContract.ts'); fs.writeFileSync(file, "M55_CURRENT_RUNTIME_STATE\npreResultThemeSelection: false\nM55_TARGET_COMMERCIAL_CONTRACT\npreResultThemeSelection: true\nM55_DEFERRED_RUNTIME_ASSERTIONS\nACTIVE_LANE: '個人無料→個人Premiumファネルの一括実装'"); }); assert.equal(inspect(root).status, 'HOLD'); });
test('14 target presented as live → HOLD', () => { const root = fixture((dir) => replace(dir, 'docs/ssot/M55_SELF_FUNNEL_CONTRACT.md', 'Current runtime (NOT target)', 'Current runtime')); assert.equal(inspect(root).status, 'HOLD'); });
test('15 duplicate next single action → HOLD', () => { const root = fixture((dir) => { const file = path.join(dir, 'docs/ssot/M55_CURRENT_STATE.md'); fs.appendFileSync(file, `\n| **postMergeNextSingleAction** | ${ACTION} |`); }); assert.equal(inspect(root).status, 'HOLD'); });
test('16 remote credential redaction', () => assert.equal(redactRemote('https://token@example.com/a'), 'https://[REDACTED]@example.com/a'));
test('17 HTML script escaping', () => assert.equal(htmlEscape('<script>alert(1)</script>'), '&lt;script&gt;alert(1)&lt;/script&gt;'));
test('18 deterministic symlink escape rejection without filesystem privilege', () => assert.throws(() => validateAuthorityPath('/repo', '/repo/authority.md', '/outside/authority.md', 'authority.md'), /AUTHORITY_SYMLINK_ESCAPE/));
test('18a lexical escape has distinct reason', () => assert.throws(() => validateAuthorityPath('/repo', '/outside/authority.md', '/outside/authority.md', 'authority.md'), /AUTHORITY_PATH_ESCAPE/));
test('18b real symlink escape rejection where supported', (t) => { const root = fixture(); const outside = path.join(os.tmpdir(), `m55-outside-${Date.now()}`); fs.writeFileSync(outside, 'token-like-value'); try { fs.rmSync(path.join(root, 'AGENTS.md')); fs.symlinkSync(outside, path.join(root, 'AGENTS.md')); assert.throws(() => safeRead(root, 'AGENTS.md'), /AUTHORITY_SYMLINK_ESCAPE/); } catch (error) { if (error.code === 'EPERM') t.skip('host does not permit symlink creation'); else throw error; } finally { fs.rmSync(root, { recursive: true, force: true }); fs.rmSync(outside, { force: true }); } });
test('19 stable JSON ordering', () => assert.equal(stableJson({ z: 1, a: { y: 2, b: 3 } }), '{"a":{"b":3,"y":2},"z":1}'));
test('20 usage error exit 2', () => assert.equal(spawnSync(process.execPath, ['scripts/m55-handoff/audit.mjs'], { cwd: ROOT, env: process.env, shell: false, windowsHide: true }).status, 2));
test('21 HOLD exit 1 and 22 clean success exit 0', () => { const hold = spawnSync(process.execPath, ['scripts/m55-handoff/audit.mjs', '--repo', '.'], { cwd: ROOT }); assert.equal(hold.status, 1); const root = gitFixture(); const out = fs.mkdtempSync(path.join(os.tmpdir(), 'm55-handoff-out-')); try { const ready = spawnSync(process.execPath, [path.join(ROOT, 'scripts/m55-handoff/audit.mjs'), '--repo', root, '--out', out], { encoding: 'utf8' }); assert.equal(ready.status, 0, `${ready.stdout}${ready.stderr}`); const json = fs.readFileSync(path.join(out, 'handoff-report.json'), 'utf8'); assert.ok(!json.includes('token-like-secret')); assert.ok(json.includes('[REDACTED]')); } finally { fs.rmSync(root, { recursive: true, force: true }); fs.rmSync(out, { recursive: true, force: true }); } assert.equal(exitCodeForStatus('READY_WITH_WARNINGS'), 0); });
test('23 default output leaves Git status unchanged', () => { const before = execFileSync('git', ['status', '--porcelain'], { cwd: ROOT, encoding: 'utf8' }); const result = spawnSync(process.execPath, ['scripts/m55-handoff/audit.mjs', '--repo', '.'], { cwd: ROOT }); const after = execFileSync('git', ['status', '--porcelain'], { cwd: ROOT, encoding: 'utf8' }); assert.equal(result.status, 1); assert.equal(after, before); });
test('parser rejects duplicate active lane, empty values, and malformed registry', () => { const duplicate = fixture((dir) => fs.appendFileSync(path.join(dir, 'lib/m55/contracts/m55CommercialFunnelContract.ts'), "\nACTIVE_LANE: '個人無料→個人Premiumファネルの一括実装'")); assert.equal(inspect(duplicate).status, 'HOLD'); const empty = fixture((dir) => replace(dir, 'docs/ssot/M55_CURRENT_STATE.md', ACTION, '')); assert.equal(inspect(empty).status, 'HOLD'); const malformed = fixture((dir) => replace(dir, 'docs/ssot/M55_WORKTREE_REGISTRY.md', '| lifecycle | **ACTIVE** + **PRIMARY_MAIN_HOME** (designation) |', '| lifecycle |  |')); assert.equal(inspect(malformed).status, 'HOLD'); });
test('worktree parsing remains deterministic', () => { const parsed = parseWorktrees('worktree /b\nHEAD b\nbranch refs/heads/b\n\nworktree /a\nHEAD a\nbranch refs/heads/a\n'); assert.deepEqual(parsed.map(({ path: value, head, branch, detached }) => ({ path: value, head, branch, detached })), [{ path: '/a', head: 'a', branch: 'a', detached: false }, { path: '/b', head: 'b', branch: 'b', detached: false }]); });
test('generic non-M55 adapter uses the same status reducer', () => { assert.equal(inspectNebula({ clean: true, authorityText: '## Active delivery lane\n## Next action' }).status, 'READY'); assert.equal(inspectNebula({ clean: false, authorityText: '## Active delivery lane\n## Next action' }).status, 'HOLD'); });
test('handoff packet writes all four files and HOLD bootstrap blocks implementation', () => { const root = gitFixture(); const out = fs.mkdtempSync(path.join(os.tmpdir(), 'm55-packet-')); try { fs.writeFileSync(path.join(root, 'untracked.txt'), 'fixture'); assert.equal(spawnSync(process.execPath, [path.join(ROOT, 'scripts/m55-handoff/audit.mjs'), '--repo', root, '--out', out]).status, 1); for (const file of ['handoff-report.json', 'handoff-report.html', 'handoff.md', 'agent-bootstrap.txt']) assert.ok(fs.existsSync(path.join(out, file))); assert.match(fs.readFileSync(path.join(out, 'agent-bootstrap.txt'), 'utf8'), /DO NOT BEGIN IMPLEMENTATION/); assert.match(fs.readFileSync(path.join(out, 'handoff.md'), 'utf8'), /DO_NOT_USE worktrees/); } finally { fs.rmSync(root, { recursive: true, force: true }); fs.rmSync(out, { recursive: true, force: true }); } });
test('valid older next-single-action authority text parses structurally', () => { const older = 'PRIMARY_MAIN_HOME で `main` checkout → `origin/main` merge SHA 確認 → Self Funnel 実装 PR スコープ確定'; const root = fixture((dir) => replace(dir, 'docs/ssot/M55_CURRENT_STATE.md', ACTION, older)); const report = inspect(root); assert.equal(report.status, 'READY'); assert.equal(report.authority.nextSingleAction, older); assert.equal(report.authority.parseStatus, 'PARSED'); });
test('malformed authority does not emit registry-dependent cascade noise', () => { const root = fixture((dir) => replace(dir, 'docs/ssot/M55_CURRENT_STATE.md', ACTION, '')); const report = inspect(root); assert.deepEqual(report.reasonCodes, ['MALFORMED_AUTHORITY']); assert.equal(report.authority.parseStatus, 'UNAVAILABLE'); assert.match(report.authority.parseReason, /next-single-action/); assert.ok(!report.checks.some((item) => item.id === 'worktree:unregistered' || item.id === 'worktree:prohibited')); });
test('conflicting registry entries fail closed without unregistered duplicates', () => { const root = fixture((dir) => { const registry = path.join(dir, 'docs/ssot/M55_WORKTREE_REGISTRY.md'); fs.appendFileSync(registry, '\n### WT-002 — conflict\n| Field | Value |\n|---|---|\n| path | `/fixture` |\n| branch | `other` |\n| lifecycle | **ACTIVE** |\n'); }); const report = inspect(root); assert.deepEqual(report.reasonCodes, ['MALFORMED_WORKTREE_REGISTRY']); assert.ok(!report.checks.some((item) => item.id === 'worktree:unregistered')); });
test('parsed current and target state remain explicitly distinct', () => { const report = inspect(fixture()); assert.equal(report.authority.fieldAvailability.currentState.status, 'AVAILABLE'); assert.equal(report.authority.fieldAvailability.targetState.status, 'AVAILABLE'); assert.notEqual(report.authority.currentState, report.authority.targetState); assert.match(report.authority.targetState, /not current runtime/); });
test('all four HOLD outputs preserve semantic parity and public identity safety', () => { const root = gitFixture(); const out = fs.mkdtempSync(path.join(os.tmpdir(), 'm55 parity-')); try { fs.writeFileSync(path.join(root, 'untracked.txt'), 'fixture'); const result = spawnSync(process.execPath, [path.join(ROOT, 'scripts/m55-handoff/audit.mjs'), '--repo', root, '--out', out], { encoding: 'utf8' }); assert.equal(result.status, 1, `${result.stdout}${result.stderr}`); const json = fs.readFileSync(path.join(out, 'handoff-report.json'), 'utf8'); const report = JSON.parse(json); const publicCopies = ['handoff-report.html', 'handoff.md', 'agent-bootstrap.txt'].map((file) => fs.readFileSync(path.join(out, file), 'utf8')); const allCopies = [json, ...publicCopies]; for (const copy of allCopies) { assert.match(copy, /M55 Control Plane/); assert.ok(copy.includes(report.status)); assert.ok(copy.includes(report.repository.branch)); assert.ok(copy.includes(report.repository.head)); for (const code of report.reasonCodes) assert.ok(copy.includes(code), `${code} missing from packet output`); } for (const copy of publicCopies) { assert.doesNotMatch(copy, /\/Users\/|\\Users\\/i); assert.ok(!copy.includes(root)); assert.match(copy, /Implementation permission:[^\n]{0,30}NO/i); assert.doesNotMatch(copy, /YES_WITHIN_DOCUMENTED_AUTHORITY/); assert.match(copy, /GIT_DIRTY/); } assert.equal(report.evidenceClassification, 'PRIVATE_MACHINE_LOCAL'); assert.equal(report.implementationPermission, 'NO'); assert.ok(report.reasonDetails.some((detail) => detail.code === 'GIT_DIRTY')); } finally { fs.rmSync(root, { recursive: true, force: true }); fs.rmSync(out, { recursive: true, force: true }); } });
test('unavailable authority fields carry the parse reason in every HOLD output', () => { const root = gitFixture(); const out = fs.mkdtempSync(path.join(os.tmpdir(), 'm55 unavailable-')); try { replace(root, 'docs/ssot/M55_CURRENT_STATE.md', ACTION, ''); const result = spawnSync(process.execPath, [path.join(ROOT, 'scripts/m55-handoff/audit.mjs'), '--repo', root, '--out', out], { encoding: 'utf8' }); assert.equal(result.status, 1); const copies = ['handoff-report.json', 'handoff-report.html', 'handoff.md', 'agent-bootstrap.txt'].map((file) => fs.readFileSync(path.join(out, file), 'utf8')); for (const copy of copies) { assert.match(copy, /MALFORMED_AUTHORITY/); assert.match(copy, /next-single-action/); assert.doesNotMatch(copy, /WORKTREE_UNREGISTERED|WORKTREE_PROHIBITED/); } assert.match(copies[3], /^HOLD — DO NOT BEGIN IMPLEMENTATION\./); assert.match(copies[3], /Active lane: UNAVAILABLE/); assert.match(copies[3], /Current state: UNAVAILABLE/); assert.match(copies[3], /Target state: UNAVAILABLE/); } finally { fs.rmSync(root, { recursive: true, force: true }); fs.rmSync(out, { recursive: true, force: true }); } });
test('public packet renderers redact local paths and embedded remote credentials', () => { const report = { projectIdentity: 'M55 Control Plane', targetRepositoryDisplayIdentity: 'M55 product repository', status: 'HOLD', reasonCodes: ['WORKTREE_UNREGISTERED'], reasonDetails: [{ code: 'WORKTREE_UNREGISTERED', level: 'FAIL', message: 'Missing.', details: { paths: ['/Users/example/Documents/private-repo'], remote: 'https://secret@example.invalid/repo.git' } }], implementationPermission: 'NO', nextAction: 'Resolve.', prohibitedActions: ['Implementation while HOLD'], generatedAt: '2026-01-01T00:00:00.000Z', checks: [], repository: { branch: 'main', head: 'abc' }, authority: { parseStatus: 'PARSED', parseReason: null, readOrder: ['AGENTS.md'], nextSingleAction: 'Review.', activeLane: 'Synthetic lane', currentState: 'Current.', targetState: 'Target.', prohibitedLanes: ['none'], humanDecisionsRequired: [], doNotUseWorktrees: ['/Users/example/Documents/private-repo'], fieldAvailability: { humanDecisions: { status: 'UNAVAILABLE', reason: 'No declaration.' } } } }; for (const copy of [renderHtml(report), handoffMarkdown(report), agentBootstrap(report)]) { assert.doesNotMatch(copy, /\/Users\/|\/Users\/example|secret@/i); assert.match(copy, /\[REDACTED\]@example\.invalid/); } });
test('judge mode writes canonical five-scenario packets with full HTML contract', () => { assert.equal(spawnSync(process.execPath, [path.join(ROOT, 'scripts/m55-handoff/demo.mjs')], { env: process.env, shell: false, windowsHide: true }).status, 0); const out = path.join(os.tmpdir(), 'm55-control-plane-demo'); for (const name of ['CLEAN_READY', 'DOCUMENTED_TRANSITION_WARNING', 'DIRTY_HOLD', 'UNEXPLAINED_DRIFT_HOLD', 'MISSING_AUTHORITY_HOLD']) { const html = fs.readFileSync(path.join(out, name, 'handoff-report.html'), 'utf8'); assert.match(html, /Next single action:|Prohibited next action:|Control Plane · evidence|Commit:/); assert.ok(fs.existsSync(path.join(out, name, 'agent-bootstrap.txt'))); } assert.match(fs.readFileSync(path.join(out, 'DIRTY_HOLD', 'agent-bootstrap.txt'), 'utf8'), /^HOLD — DO NOT BEGIN IMPLEMENTATION\.$/m); });
test('Windows Git resolver honors PATH and PATHEXT', () => { const found = resolveGitExecutable({ platform: 'win32', env: { PATH: 'C:\\Program Files\\Git\\cmd', PATHEXT: '.EXE;.CMD' }, existsSync: (candidate) => candidate.endsWith('git.exe') }); assert.equal(found, path.win32.join('C:\\Program Files\\Git\\cmd', 'git.exe')); });
test('canonical HTML escapes injected values', () => { const html = renderHtml({ status: 'HOLD', reasonCodes: ['<script>'], generatedAt: '2026-01-01T00:00:00.000Z', checks: [], repository: { head: '<script>' }, authority: { nextSingleAction: '<script>', prohibitedLanes: ['<script>'] } }); assert.ok(!html.includes('<script>')); assert.match(html, /&lt;script&gt;/); });
test('win32 slash and backslash identities are equivalent', () => { const options = { targetPlatform: 'win32', filesystemResolution: false }; assert.equal(canonicalPathIdentity('C:\\Work Tree\\Repo', options), canonicalPathIdentity('C:/Work Tree/Repo', options)); });
test('win32 drive-letter case identities are equivalent', () => { const options = { targetPlatform: 'win32', filesystemResolution: false }; assert.equal(canonicalPathIdentity('C:\\Work Tree\\Repo', options), canonicalPathIdentity('c:\\Work Tree\\Repo', options)); });
test('win32 path comparison is case-insensitive', () => { const options = { targetPlatform: 'win32', filesystemResolution: false }; assert.equal(canonicalPathIdentity('C:\\Work Tree\\Repo', options), canonicalPathIdentity('C:\\WORK TREE\\REPO', options)); });
test('win32 spaces are preserved', () => { const identity = canonicalPathIdentity('C:\\Work Tree\\Repo', { targetPlatform: 'win32', filesystemResolution: false }); assert.match(identity, /work tree/); assert.notEqual(identity, canonicalPathIdentity('C:\\WorkTree\\Repo', { targetPlatform: 'win32', filesystemResolution: false })); });
test('win32 trailing separators are normalized', () => { const options = { targetPlatform: 'win32', filesystemResolution: false }; assert.equal(canonicalPathIdentity('C:\\Work Tree\\Repo\\', options), canonicalPathIdentity('C:\\Work Tree\\Repo', options)); });
test('darwin preserves POSIX root', () => assert.equal(canonicalPathIdentity('/tmp/Work Tree/', { targetPlatform: 'darwin', filesystemResolution: false }), '/tmp/Work Tree'));
test('darwin preserves case', () => assert.equal(canonicalPathIdentity('/tmp/Work Tree', { targetPlatform: 'darwin', filesystemResolution: false }), '/tmp/Work Tree'));
test('darwin case-different paths remain different', () => { const options = { targetPlatform: 'darwin', filesystemResolution: false }; assert.notEqual(canonicalPathIdentity('/tmp/Work Tree', options), canonicalPathIdentity('/tmp/work tree', options)); });
test('linux preserves POSIX root and case', () => { const options = { targetPlatform: 'linux', filesystemResolution: false }; assert.equal(canonicalPathIdentity('/tmp/Work Tree/', options), '/tmp/Work Tree'); assert.notEqual(canonicalPathIdentity('/tmp/Work Tree', options), canonicalPathIdentity('/tmp/work tree', options)); });
test('target cwd makes relative identities host-independent', () => { assert.equal(canonicalPathIdentity('Repo', { targetPlatform: 'darwin', targetCwd: '/tmp/Work Tree', filesystemResolution: false }), '/tmp/Work Tree/Repo'); assert.equal(canonicalPathIdentity('Repo', { targetPlatform: 'win32', targetCwd: 'D:\\Work Tree', filesystemResolution: false }), 'd:\\work tree\\repo'); });
test('foreign simulation never invokes native realpath when filesystem resolution is unavailable', () => { let called = false; const identity = canonicalPathIdentity('/tmp/Work Tree', { targetPlatform: 'darwin', filesystemResolution: false, realpathSync: () => { called = true; return '/wrong'; } }); assert.equal(identity, '/tmp/Work Tree'); assert.equal(called, false); });
test('injected target resolver is used only when filesystem resolution is available', () => { let called = false; const identity = canonicalPathIdentity('/virtual/link', { targetPlatform: 'linux', filesystemResolution: true, realpathSync: (value) => { called = value === '/virtual/link'; return '/virtual/real'; } }); assert.equal(identity, '/virtual/real'); assert.equal(called, true); });
test('genuinely different canonical paths remain different', () => { const options = { targetPlatform: 'win32', filesystemResolution: false }; assert.notEqual(canonicalPathIdentity('C:\\Work Tree\\Repo', options), canonicalPathIdentity('C:\\Work Tree\\Other', options)); });
test('zero-install Judge Mode runs without node_modules', () => { const isolated = fs.mkdtempSync(path.join(os.tmpdir(), 'control plane zero install-')); try { fs.mkdirSync(path.join(isolated, 'scripts'), { recursive: true }); fs.cpSync(path.join(ROOT, 'scripts/m55-handoff'), path.join(isolated, 'scripts/m55-handoff'), { recursive: true }); assert.ok(!fs.existsSync(path.join(isolated, 'node_modules'))); const result = spawnSync(process.execPath, [path.join(isolated, 'scripts/m55-handoff/demo.mjs')], { cwd: isolated, env: process.env, shell: false, windowsHide: true }); assert.equal(result.status, 0, `${result.stdout || ''}${result.stderr || ''}`); } finally { fs.rmSync(isolated, { recursive: true, force: true }); } });
test('public samples contain no local username or machine path', () => { for (const file of fs.readdirSync(path.join(ROOT, 'scripts/m55-handoff/samples'))) { const source = fs.readFileSync(path.join(ROOT, 'scripts/m55-handoff/samples', file), 'utf8'); assert.doesNotMatch(source, /lexsia|\\Users\\|\/Users\//i); } });
