import fs from 'node:fs';
import path from 'node:path';
import { htmlEscape, stableJson } from './engine.mjs';

export function renderHtml(report) {
  const rows = report.checks.map((check) => `<tr><td>${htmlEscape(check.level)}</td><td>${htmlEscape(check.id)}</td><td>${htmlEscape(check.message)}</td></tr>`).join('');
  const reasons = report.reasonCodes.length ? report.reasonCodes.join(', ') : 'No blocking or warning reasons.';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Control Plane Handoff Report</title><style>body{margin:0;background:#101c31;color:#f7f0e3;font:17px/1.55 Georgia,serif}main{max-width:1080px;margin:auto;padding:44px 28px}header{border-top:7px solid ${report.status==='HOLD'?'#ff836f':report.status==='READY'?'#63c7b8':'#f2bf62'};padding-top:22px}h1{font-size:clamp(2.2rem,7vw,4.8rem);line-height:1;margin:.1em 0}.eyebrow{color:#83d1c7;text-transform:uppercase;letter-spacing:.12em;font:700 .75rem ui-monospace,monospace}.reason{font-size:1.25rem;max-width:48rem}.brief{border-left:3px solid #83d1c7;padding:8px 18px;margin:28px 0}h2{margin-top:34px}table{width:100%;border-collapse:collapse;margin-top:16px;background:#182944}td,th{padding:11px;border-bottom:1px solid #38516f;text-align:left;vertical-align:top}code{font-family:ui-monospace,monospace;word-break:break-all}@media(max-width:390px){main{padding:26px 18px}table{font-size:.82rem}td,th{padding:8px}.brief{margin:20px 0}}</style></head><body><main><header><p class="eyebrow">Control Plane · evidence ${htmlEscape(report.generatedAt)}</p><h1>${htmlEscape(report.status)}</h1><p class="reason">${htmlEscape(reasons)}</p><div class="brief"><strong>Next single action:</strong> ${htmlEscape(report.authority.nextSingleAction || 'Resolve authority before acting.')}<br><strong>Prohibited next action:</strong> ${htmlEscape((report.authority.prohibitedLanes || ['implementation']).join(', '))}<br><strong>Commit:</strong> <code>${htmlEscape(report.repository.head)}</code></div></header><section aria-labelledby="checks"><h2 id="checks">Evidence</h2><table><thead><tr><th>Result</th><th>Check</th><th>Detail</th></tr></thead><tbody>${rows}</tbody></table></section></main></body></html>`;
}

export function handoffMarkdown(report) { const a = report.authority; return `# Control Plane Handoff\n\nStatus: **${report.status}**\n\n- Repository authority: ${a.readOrder?.join(' → ') || 'unavailable'}\n- Branch / HEAD: \`${report.repository.branch}\` / \`${report.repository.head}\`\n- Active lane: ${a.activeLane || 'unavailable'}\n- Completed GREEN: ${a.completedGreen}\n- Current runtime debts: ${(a.runtimeDebts || []).join('; ') || 'unavailable'}\n- Target state: ${a.targetState}\n- Next single action: ${a.nextSingleAction || 'unavailable'}\n- Prohibited lanes: ${(a.prohibitedLanes || []).join(', ')}\n- DO_NOT_USE worktrees: ${(a.doNotUseWorktrees || []).join(', ') || 'none'}\n- Human decisions required: ${(a.humanDecisionsRequired || []).join(', ')}\n\nFirst allowed read-only commands: \`git status --short --branch\`, \`git worktree list\`, \`npm run audit:m55-handoff -- --repo .\`.\n\n${report.status === 'HOLD' ? '**HOLD: do not begin implementation. Resolve the listed reason codes, then rerun the audit.**' : 'Proceed only within the documented allowed lane.'}\n`; }

export function writeHandoffPacket(out, report) {
  fs.mkdirSync(out, { recursive: true });
  fs.writeFileSync(path.join(out, 'handoff-report.json'), `${stableJson(report)}\n`);
  fs.writeFileSync(path.join(out, 'handoff-report.html'), renderHtml(report));
  fs.writeFileSync(path.join(out, 'handoff.md'), handoffMarkdown(report));
  fs.writeFileSync(path.join(out, 'agent-bootstrap.txt'), `${report.status === 'HOLD' ? 'HOLD — DO NOT BEGIN IMPLEMENTATION.\n' : 'Read authority before acting.\n'}${report.status === 'HOLD' ? 'Resolve the listed HOLD reason codes and rerun the audit.\n' : 'Read handoff.md, then run only: git status --short --branch; git worktree list; npm run audit:m55-handoff -- --repo .\n'}`);
}
